name: 'Bink'
version: '1.0.0'
config-version: 2

profile: 'Bink_New'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

models:
  Bink:
    prod:
      +database: "PROD"
      bink:
        +schema: "BINK"
        materialized: table
      bink_secure:
        +schema: "BINK_SECURE"
        materialized: table
      service_data:
        +schema: "SERVICE_DATA"
        materialized: table

    staging:
      +database: "STAGING"
      staging:
        +schema: "STAGING"
        materialized: view
      transformation:
        +schema: "TRANSFORMATION"
        materialized: view
    
    metrics_staging:
      +database: "METRICS_STAGING"
      +materialized: view
      warehouse:
        +schema: "WAREHOUSE"      
      lookup:
        +schema: "LOOKUP"
      retailer_lookup:
        +schema: "RETAILER_LOOKUP"
      metrics_transformation:
        +schema: "TRANSFORMATION"

    metrics:
      +database: "METRICS"
      loyalty_cards:
        +schema: "LOYALTY_CARDS"
        materialized: table
      transactions:
        +schema: "TRANSACTIONS"
        materialized: table
      users:
        +schema: "USERS"
        materialized: table
      voucher:
        +schema: "VOUCHER"
        materialized: table
      jira:
        +schema: "JIRA"
        materialized: table

    output:
      +database: "OUTPUT"
      lbg:
        +schema: "LBG"
        materialized: table
      commercial:
        +schema: "COMMERCIAL"
        materialized: table
      ext:
        +schema: "EXT"
        materialized: table
      jira:
        +schema: "JIRA"
        materialized: table
      retailer__the_works:
        +schema: "RETAILER__THE_WORKS"
        materialized: table
      retailer__itsu:
        +schema: "RETAILER__ITSU"
        materialized: table
      retailer__slim_chickens:
        +schema: "RETAILER__SLIM_CHICKENS"
        materialized: table
      retailer__stonegate:
        +schema: "RETAILER__STONEGATE"
        materialized: table
      retailer__squaremeal:
        +schema: "RETAILER__SQUAREMEAL"
        materialized: table
      retailer__viator:
        +schema: "RETAILER__VIATOR"
        materialized: table
      retailer__tgi_fridays:
        +schema: "RETAILER__TGI_FRIDAYS"
        materialized: table
      self_service:
        +schema: "SELF_SERVICE"
        materialized: table

seeds:
  Bink:
    lookup:
      +database: "RAW" #to be moved to raw eventually
      +schema: "BINK_LOOKUP"
    retailer:
      +database: "RAW"
      +schema: "RETAILER_LOOKUP"
        
  elementary:
    +database: 'MONITORING'
    +schema: 'MONITORING'
    +materialized: table
    +transient: false
vars:
 dbt_artifacts_database: 'DEV'
 dbt_artifacts_schema: 'MONITORING'
 qa_data_suffix: ''
 retailor_live_dates: {"The Works": ["2023-08-22 00:00:00", "9999-12-31 00:00:00"], 
                  "itsu": ["2023-09-11 22:40:00", "9999-12-31 00:00:00"], 
                  "Slim Chickens": ["2023-11-01 00:00:00", "9999-12-31 00:00:00"], 
                  "Iceland": ["2021-01-01 00:00:00", "2023-10-10 00:00:00"],
                  "Stonegate Group": ["2023-11-06 00:00:00", "9999-12-31 00:00:00"],
                  "Viator":["2023-02-07 00:00:00","9999-12-31 00:00:00"]}
 retailor_exclusion_lists: {"The Works": {"CHANNEL": ['BARCLAYS', 'BINK']}}
