{{ config(enabled = false)}}

WITH wasabi_grid AS (
    SELECT *
    FROM {{source('MERCHANT','WASABI_GRID')}}
)

, wasabi_grid_select AS (
    SELECT
        DATE
//        ,JOINS__BARCLAYS__JOINS_SCHEME
//        ,JOINS__BARCLAYS__OPTED_IN_TO_MARKETING
//        ,JOINS__BARCLAYS__PERCENT_OPTED_IN_TO_MARKETING
//        ,JOINS__BARCLAYS__JOINS_AND_PLL_ENABLED_LINKED_PAYMENT_CARD
//        ,JOINS__BINK__JOINS_SCHEME
//        ,JOINS__BINK__OPTED_IN_TO_MARKETING
//        ,JOINS__BINK__PERCENT_OPTED_IN_TO_MARKETING
//        ,JOINS__BINK__JOINS_AND_PLL_ENABLED_LINKED_PAYMENT_CARD
        ,JOINS__TOTAL__JOINS_SCHEME
        ,JOINS__TOTAL__JOINS_SCHEME_AND_PLL_ENABLED
//        ,JOINS__TOTAL__BILLABLE_JOINS
        ,JOINS__TOTAL__CUMULATIVE_JOINS_SCHEME_AND_PLL_ENABLED
        ,ADDS__BARCLAYS__ADDS_WITH_PAYMENT_CARD
        ,ADDS__BARCLAYS__ADDS_WITHOUT_A_PAYMENT_CARD
//        ,ADDS__BARCLAYS__ADDS_WITH_AND_WITHOUT_A_PAYMENT_CARD
        ,ADDS__BINK__ADDS_WITH_PAYMENT_CARD
//        ,ADDS__BINK__ADDS_WITHOUT_A_PAYMENT_CARD
//        ,ADDS__BINK__ADDS_WITH_AND_WITHOUT_A_PAYMENT_CARD
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__BARCLAYS__LIVE_USERS__LOYALTY_IDS
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__BINK__LIVE_USERS__LOYALTY_IDS
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__TOTAL__LIVE_USERS__LOYALTY_IDS
//        ,ACTIVE_USERS_BILLABLE
//        ,PERCENT_ACTIVE_VERSUS_TOTAL_LIVE_USERS
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__BARCLAYS_ONLY
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__BINK_ONLY
//        ,LIVE_USERS_LOYALTY_IDS_PLL_LINK_EXC_TESTERS__BARCLAYS_AND_BINK
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__MATCHED_BUT_NO_STAMP
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__MATCHED_STAMP_AWARDED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__MATCHED_NO_RESPONSE_RECEIVED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__TOTAL_MATCHED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__SPOTTED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_INC_TESTERS__TOTAL
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__MATCHED_BUT_NO_STAMP
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__MATCHED_STAMP_AWARDED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__MATCHED_NO_RESPONSE_RECEIVED
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__TOTAL_MATCHED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__SPOTTED
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__TOTAL
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__AVERAGE_TRANSACTION_VALUE
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__TOTAL_TRANSACTION_VALUE_ACTIVE_USERS
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__AVERAGE_NUMBER_OF_MATCHED_TRANSACTIONS_PER_CUSTOMER_TOTAL
        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__AVERAGE_NUMBER_OF_MATCHED_TRANSACTIONS_PER_CUSTOMERS_ACTIVE
//        ,TRANSACTIONS_FOR_MI_ALL_TRANS_EXC_TESTERS__PERCENT_OF_TRANSACTIONS_ISSUING_A_STAMP
//        ,VOUCHERS_INC_TESTERS__ISSUED
//        ,VOUCHERS_INC_TESTERS__REDEEMED
//        ,VOUCHERS_INC_TESTERS__LIVE
//        ,VOUCHERS_INC_TESTERS__TOTAL_ISSUED
//        ,VOUCHERS_INC_TESTERS__TOTAL_REDEEMED
//        ,VOUCHERS_INC_TESTERS__TOTAL_EXPIRED
        ,VOUCHERS_EXC_TESTERS__ISSUED
        ,VOUCHERS_EXC_TESTERS__REDEEMED
//        ,VOUCHERS_EXC_TESTERS__LIVE
        ,VOUCHERS_EXC_TESTERS__TOTAL_ISSUED
        ,VOUCHERS_EXC_TESTERS__TOTAL_REDEEMED
//        ,VOUCHERS_EXC_TESTERS__TOTAL_EXPIRED
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__0
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__1
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__2
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__3
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__4
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__5
//        ,NUMBER_OF_CUSTOMERS_WITH_EACH_STAMP_TOTAL__AT_END_OF_THE_MONTH_EXC_TESTERS__6
    FROM
         wasabi_grid
)

SELECT *
FROM wasabi_grid_select
