/*
CREATED BY:         CHRISTOPHER MITCHELL
CREATED DATE:       2023-11-01
LAST MODIFIED BY:
LAST MODIFIED DATE:

DESCRIPTION:
    CONVERT THE TRANS__AVG__MONTHLY_RETAILER_CHANNEL TABLE TO GROWTH METRICS.
PARAMETERS:
    SOURCE_OBJECT       - TRANS__AVG__MONTHLY_RETAILER_CHANNEL
*/

{{convert_to_growth("trans__avg__monthly_retailer_channel",
                    ["DATE", "LOYALTY_PLAN_NAME", "LOYALTY_PLAN_COMPANY"],
                    [],
                    ["LOYALTY_PLAN_NAME", "LOYALTY_PLAN_COMPANY"],
                    "DATE" )
}}
