CREATE OR REPLACE TABLE "RAW"."BINK_LOOKUP"."ACCOUNT_STATUS"
(CODE INTEGER
,STATUS STRING
,STATUS_GROUP STRING
,JOURNEY_TYPE STRING
,STATUS_TYPE STRING
,STATUS_ROLLUP STRING
,STATUS_V2 STRING
,ERROR_SLUG_V2 STRING
)
;