/*
Created by:         Anand Bhakta
Created date:       2023-02-05
Last modified by:   
Last modified date: 

Description:
    Rewrite of the LL table lc_joins_links_snapshot and lc_joins_links containing both snapshot and daily absolute data of all link and join journeys split by merchant.
Notes:
    This code can be made more efficient if the start is pushed to the trans__lbg_user code and that can be the source for the majority of the dashboards including user_loyalty_plan_snapshot and user_with_loyalty_cards
Parameters:
    source_object       - src__fact_lc_add
                        - src__fact_lc_removed
                        - src__dim_loyalty_card
                        - src__dim_date
*/

WITH lc_events AS (
    SELECT *
    FROM {{ref('lc_trans')}}
)

,dim_date AS (
    SELECT *
    FROM {{ref('src__dim_date')}}
    WHERE
        DATE >= (SELECT MIN(FROM_DATE) FROM lc_events)
        AND DATE <= CURRENT_DATE()
)
        
,count_up_snap AS (
  SELECT
    d.DATE
    ,u.CHANNEL
    ,u.BRAND
    ,u.LOYALTY_PLAN_NAME
    ,u.LOYALTY_PLAN_COMPANY
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_SUCCESS_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_FAILED_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_PENDING_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_REMOVED_STATE
  
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_SUCCESS_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_FAILED_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_PENDING_STATE
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_REMOVED_STATE
FROM lc_events u
LEFT JOIN dim_date d
    ON d.DATE >= DATE(u.FROM_DATE)
    AND d.DATE < COALESCE(DATE(u.TO_DATE), '9999-12-31')
GROUP BY
    d.DATE
    ,u.BRAND
    ,u.LOYALTY_PLAN_NAME
    ,u.LOYALTY_PLAN_COMPANY
HAVING DATE IS NOT NULL
)    

,count_up_abs AS (
  SELECT
    d.DATE
    ,u.CHANNEL
    ,u.BRAND
    ,u.LOYALTY_PLAN_NAME
    ,u.LOYALTY_PLAN_COMPANY
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_REQUESTS
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_FAILS
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_SUCCESSES
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'JOIN' THEN 1 END),0) AS JOIN_DELETES
  
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_REQUESTS
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_FAILS
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_SUCCESSES
        ,COALESCE(SUM(CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'LINK' THEN 1 END),0) AS LINK_DELETES


        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'JOIN' THEN u.USER_REF END),0) AS JOIN_REQUESTS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'JOIN' THEN u.USER_REF END),0) AS JOIN_FAILS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'JOIN' THEN u.USER_REF END),0) AS JOIN_SUCCESSES_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'JOIN' THEN u.USER_REF END),0) AS JOIN_DELETES_UNIQUE_USERS
  
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'REQUEST' AND ADD_JOURNEY = 'LINK' THEN u.USER_REF END),0) AS LINK_REQUESTS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'FAILED' AND ADD_JOURNEY = 'LINK' THEN u.USER_REF END),0) AS LINK_FAILS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'SUCCESS' AND ADD_JOURNEY = 'LINK' THEN u.USER_REF END),0) AS LINK_SUCCESSES_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'DELETE' AND ADD_JOURNEY = 'LINK' THEN u.USER_REF END),0) AS LINK_DELETES_UNIQUE_USERS

        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'REQUEST' THEN u.USER_REF END),0) AS REQUESTS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'FAILED' THEN u.USER_REF END),0) AS FAILS_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'SUCCESS' THEN u.USER_REF END),0) AS SUCCESSES_UNIQUE_USERS
        ,COALESCE(COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'DELETE' THEN u.USER_REF END),0) AS DELETES_UNIQUE_USERS

FROM lc_events u
LEFT JOIN dim_date d
    ON d.DATE = u.FROM_DATE
GROUP BY
    d.DATE
    ,u.BRAND
    ,u.LOYALTY_PLAN_NAME
    ,u.LOYALTY_PLAN_COMPANY
HAVING DATE IS NOT NULL
)

,all_together AS (
    SELECT
        COALESCE(a.date,s.date) DATE
        ,COALESCE(a.brand,s.brand) BRAND
        ,COALESCE(a.CHANNEL,s.CHANNEL) BRAND
        ,COALESCE(a.LOYALTY_PLAN_NAME,s.LOYALTY_PLAN_NAME) LOYALTY_PLAN_NAME
        ,COALESCE(a.LOYALTY_PLAN_COMPANY,s.LOYALTY_PLAN_COMPANY) LOYALTY_PLAN_COMPANY

        ,COALESCE(s.JOIN_SUCCESS_STATE,0) AS JOIN_SUCCESS_STATE
        ,COALESCE(s.JOIN_FAILED_STATE,0) AS JOIN_FAILED_STATE
        ,COALESCE(s.JOIN_PENDING_STATE,0) AS JOIN_PENDING_STATE
        ,COALESCE(s.JOIN_REMOVED_STATE,0) AS JOIN_REMOVED_STATE
        ,COALESCE(s.LINK_SUCCESS_STATE,0) AS LINK_SUCCESS_STATE
        ,COALESCE(s.LINK_FAILED_STATE,0) AS LINK_FAILED_STATE
        ,COALESCE(s.LINK_PENDING_STATE,0) AS LINK_PENDING_STATE
        ,COALESCE(s.LINK_REMOVED_STATE,0) AS LINK_REMOVED_STATE

        ,COALESCE(a.JOIN_REQUESTS,0) AS JOIN_REQUESTS
        ,COALESCE(a.JOIN_FAILS,0) AS JOIN_FAILS
        ,COALESCE(a.JOIN_SUCCESSES,0) AS JOIN_SUCCESSES
        ,COALESCE(a.JOIN_DELETES,0) AS JOIN_DELETES
        ,COALESCE(a.LINK_REQUESTS,0) AS LINK_REQUESTS
        ,COALESCE(a.LINK_FAILS,0) AS LINK_FAILS
        ,COALESCE(a.LINK_SUCCESSES,0) AS LINK_SUCCESSES
        ,COALESCE(a.LINK_DELETES,0) AS LINK_DELETES

        ,COALESCE(a.JOIN_REQUESTS_UNIQUE_USERS,0) AS JOIN_REQUESTS_UNIQUE_USERS
        ,COALESCE(a.JOIN_FAILS_UNIQUE_USERS,0) AS JOIN_FAILS_UNIQUE_USERS
        ,COALESCE(a.JOIN_SUCCESSES_UNIQUE_USERS,0) AS JOIN_SUCCESSES_UNIQUE_USERS
        ,COALESCE(a.JOIN_DELETES_UNIQUE_USERS,0) AS JOIN_DELETES_UNIQUE_USERS
        ,COALESCE(a.LINK_REQUESTS_UNIQUE_USERS,0) AS LINK_REQUESTS_UNIQUE_USERS
        ,COALESCE(a.LINK_FAILS_UNIQUE_USERS,0) AS LINK_FAILS_UNIQUE_USERS
        ,COALESCE(a.LINK_SUCCESSES_UNIQUE_USERS,0) AS LINK_SUCCESSES_UNIQUE_USERS
        ,COALESCE(a.LINK_DELETES_UNIQUE_USERS,0) AS LINK_DELETES_UNIQUE_USERS
    FROM count_up_abs a
    FULL OUTER JOIN count_up_snap s     
        ON a.date=s.date and a.brand = s.brand and a.loyalty_plan_name = s.loyalty_plan_name
)

,add_combine_metrics AS (
    SELECT
        DATE
        ,CHANNEL
        ,BRAND
        ,LOYALTY_PLAN_NAME
        ,LOYALTY_PLAN_COMPANY

        ,JOIN_SUCCESS_STATE                                          AS LCJ001__JOIN_SUCCESS_CUMULATIVE
        ,JOIN_FAILED_STATE                                          
        ,JOIN_PENDING_STATE                                         
        ,JOIN_REMOVED_STATE                                          AS LCJ004__JOIN_REMOVED_CUMULATIVE
        ,LINK_SUCCESS_STATE                                          AS LCL001__LINK_SUCCESS_CUMULATIVE
        ,LINK_FAILED_STATE                                          
        ,LINK_PENDING_STATE                                         
        ,LINK_REMOVED_STATE                                          AS LCL004__LINK_REMOVED_CUMULATIVE
        ,JOIN_SUCCESS_STATE+LINK_SUCCESS_STATE                       AS LC001__LC_SUCCESS_CUMULATIVE
        ,JOIN_PENDING_STATE+LINK_PENDING_STATE                       AS PENDING_STATE
        ,JOIN_FAILED_STATE+LINK_FAILED_STATE                         AS FAILED_STATE
        ,LINK_REMOVED_STATE+JOIN_REMOVED_STATE                       AS LC002__LC_REMOVED_CUMULATIVE

        ,JOIN_REQUESTS
        ,JOIN_FAILS
        ,JOIN_SUCCESSES
        ,JOIN_DELETES
        ,LINK_REQUESTS
        ,LINK_FAILS
        ,LINK_SUCCESSES
        ,LINK_DELETES
        ,JOIN_REQUESTS + LINK_REQUESTS AS REQUESTS
        ,JOIN_FAILS + LINK_FAILS AS FAILS
        ,JOIN_SUCCESSES + LINK_SUCCESSES AS LC003__LC_SUCCESS_PERIOD
        ,JOIN_DELETES + LINK_DELETES AS LC004__LC_REMOVE_PERIOD

        ,JOIN_REQUESTS_UNIQUE_USERS
        ,JOIN_FAILS_UNIQUE_USERS
        ,JOIN_SUCCESSES_UNIQUE_USERS
        ,JOIN_DELETES_UNIQUE_USERS
        ,LINK_REQUESTS_UNIQUE_USERS
        ,LINK_FAILS_UNIQUE_USERS
        ,LINK_SUCCESSES_UNIQUE_USERS
        ,LINK_DELETES_UNIQUE_USERS

    FROM all_together
)

select * 
from add_combine_metrics
